spring.application.name=scm2.0

server.baseUrl=${BASE_URL:http://localhost:8081}
server.port=${PORT:8080}
# server.port=${PORT:10000}

# PostgreSQL Config (IMPORTANT)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# spring.mail.properties.domain_name=${EMAIL_DOMAIN:http://localhost:8081}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.profiles.active=dev

# Logging
logging.level.com.smartcontact=DEBUG
