# spring.application.name=scm2.0
# server.baseUrl=${BASE_URL:http://localhost:8081}
# server.port=${SERVER_PORT:8081}

# # PostgreSQL configuration (with placeholders for environment variables)
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/scm_db_dir7}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# spring.servlet.multipart.max-file-size=10MB
# spring.servlet.multipart.max-request-size=10MB
# spring.mail.properties.domain_name=http://localhost:8081

# spring.profiles.active=dev

# # Logging
# logging.level.com.smartcontact=DEBUG

spring.application.name=scm2.0

server.baseUrl=${BASE_URL:http://localhost:8081}
server.port=${SERVER_PORT:8081}

# PostgreSQL Config (IMPORTANT)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.profiles.active=dev

# Logging
logging.level.com.smartcontact=DEBUG
